export {
  Footer,
  type FooterRootProps,
  type FooterBrandProps,
  type FooterBrandNameProps,
  type FooterTaglineProps,
  type FooterNavGridProps,
  type FooterNavColumnProps,
  type FooterNavHeadingProps,
  type FooterNavLinkProps,
  type FooterSocialRowProps,
  type FooterSocialLinkProps,
  type FooterBottomProps,
  type FooterCopyrightProps,
  type FooterLegalListProps,
  type FooterLegalLinkProps,
} from "./Footer";
export {
  footerVariants,
  footerContainerVariants,
  footerTopVariants,
  footerBrandVariants,
  footerBrandNameVariants,
  footerTaglineVariants,
  footerNavGridVariants,
  footerNavColumnVariants,
  footerNavHeadingVariants,
  footerNavListVariants,
  footerNavLinkVariants,
  footerSocialRowVariants,
  footerSocialLinkVariants,
  footerBottomVariants,
  footerCopyrightVariants,
  footerLegalListVariants,
  footerLegalLinkVariants,
  type FooterBackground,
  type FooterNavColumns,
  type FooterMaxWidth,
} from "./Footer.variants";
